name: CI

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - '**/README.md'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make files executables
        run: chmod +x ./gradlew

      - name: Ktlint
        run: ./gradlew ktlint

      - name: Detekt
        run: ./gradlew detekt

      - name: Lint
        run: ./gradlew lintDebug

      - name: Unit tests
        run: bash ./gradlew testDebugUnitTest -x lint
